### ISSUE TITLE
ShaderGraphBaker as UPM Package?

### ISSUE THREAD

**Issue by gekigengar** [omid3098/ShaderGraphBaker#1]
Hi, would be great if this could be turned into UPM package!

Thanks for this awesome tool!

https://gist.github.com/LotteMakesStuff/6e02e0ea303030517a071a1c81eb016e

**Comment by omid3098** [comment]
Hey @gekigengar and thanks for reaching out. I have no time to do that at the moment, feel free to make a pull request if you want to do that on your side.
